version: '3'

services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
  db:
    image: postgres
    environment:
      - POSTGRES_DB=khatt
      - POSTGRES_USER=khatt
      - POSTGRES_PASSWORD=khatt
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build:
      context: ./backend
    depends_on: 
      - db
    env_file:
      - ./.env.dev
    command: gunicorn -b 0.0.0.0:8000 khatt.wsgi
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    command: ng build --output-path=dist

volumes:
  postgres_data: